// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6GrU_gvv1VFMoGerkLjmzaK6GeDpI_Ko',
    appId: '1:602132050724:web:bd4d225b033b7f5b1879b1',
    messagingSenderId: '602132050724',
    projectId: 'resq-51f7f',
    authDomain: 'resq-51f7f.firebaseapp.com',
    storageBucket: 'resq-51f7f.firebasestorage.app',
    measurementId: 'G-BC4T5X0EZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6YvRqUXt0vzU1Lehq4yeX9i1wtLxR7Hw',
    appId: '1:602132050724:android:95398f760d08aaba1879b1',
    messagingSenderId: '602132050724',
    projectId: 'resq-51f7f',
    storageBucket: 'resq-51f7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3aqvO8wJMdubmrgqgvt2VHD9iPov-2j8',
    appId: '1:602132050724:ios:6d165e8eb16f0c7a1879b1',
    messagingSenderId: '602132050724',
    projectId: 'resq-51f7f',
    storageBucket: 'resq-51f7f.firebasestorage.app',
    iosBundleId: 'com.example.resqnetAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3aqvO8wJMdubmrgqgvt2VHD9iPov-2j8',
    appId: '1:602132050724:ios:6d165e8eb16f0c7a1879b1',
    messagingSenderId: '602132050724',
    projectId: 'resq-51f7f',
    storageBucket: 'resq-51f7f.firebasestorage.app',
    iosBundleId: 'com.example.resqnetAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6GrU_gvv1VFMoGerkLjmzaK6GeDpI_Ko',
    appId: '1:602132050724:web:3e2aec56fdff4f941879b1',
    messagingSenderId: '602132050724',
    projectId: 'resq-51f7f',
    authDomain: 'resq-51f7f.firebaseapp.com',
    storageBucket: 'resq-51f7f.firebasestorage.app',
    measurementId: 'G-5K9VJYHK6B',
  );
}
